var gulp        = require('gulp');
// Load all installed gulp plugins into $
var $ = require('gulp-load-plugins')();

var browserSync = require('browser-sync');

var path = require('path');

var config = {
  srcDir: 'src'
};

// Message to be prepended to all .css files generated via less
var cssMessage = [
  '/*----------------------------------------------------',
  ' | !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! |',
  ' | !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! |',
  ' | !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! |',
  ' | This file was generated by LESS.                   |',
  ' | All modifications to it will be lost, mercilessly! |',
  ' | !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! |',
  ' | !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! |',
  ' | !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! |',
  ' -----------------------------------------------------*/\n\n',
].join('\n');

var autoprefixerOptions = {
  browsers: [
    'ie >= 10',
    'ie_mob >= 10',
    'ff >= 30',
    'chrome >= 34',
    'safari >= 7',
    'opera >= 23',
    'ios >= 7',
    'android >= 4.4',
    'bb >= 10'
  ],
  cascade: false,
};

var lessErrorNotifyOptions = {
  title: 'Less compiling error',
  message: '<%= error.message %>',
  open: 'file:///<%= error.filename %>',
  sound: 'Glass',
  // Basso, Blow, Bottle, Frog, Funk, Glass, Hero,
  // Morse, Ping, Pop, Purr, Sosumi, Submarine, Tink
};

/**
 * Compile the less for the application
 * At the end, generate a ".css" file
 */
gulp.task('less', function () {

  return gulp.src(config.srcDir + '/index.less')
    .pipe($.changed(config.srcDir, { extension: '.css' }))
    .pipe($.less())
    .on('error', $.notify.onError(lessErrorNotifyOptions))
    .pipe($.rename(function (filePath) {
      filePath.basename += '.bundle';
    }))
    .pipe($.autoprefixer(autoprefixerOptions))
    .pipe($.header(cssMessage))
    .pipe(gulp.dest(config.srcDir))
    .pipe($.size({
      title: 'less',
      showFiles: true
    }));
});

/**
 * Watches files for changes and acts accordingly
 */
gulp.task('watch', function () {

  // HTML
  gulp.watch('src/**/*.html')
    .on('change', browserSync.reload);
  
  // JS 
  gulp.watch('src/**/*.js')
    .on('change', browserSync.reload);

  // LESS
  gulp.watch('src/**/*.less', ['less']);
  gulp.watch('src/**/*.css')
    .on('change', browserSync.reload);
});

// Static server
gulp.task('serve:develop', function() {

  var bs = browserSync({
    ghostMode: false,
    port: 4000,
    server: {
      baseDir: 'src',
    },
    open: true,
  });

});

gulp.task('develop', ['watch', 'serve:develop']);